version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: investdb
      MYSQL_USER: user
      MYSQL_PASSWORD: P@ssw0rd!9x#QvLz7
    ports:
      - '3307:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '3001:3001'
      - '5555:5555'
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./backend:/app
      - /app/node_modules
